spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://config-service:8888
  # rabbitmq settings
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
  # DB settings
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notification-service
    username: root
    password: 11111111
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

cloud:
  aws:
    credentials:
      ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    sqs:
      delivery-status-notification-queue:
        name: LotdizDeliveryStartNotificationQueue.fifo
        url: ${AWS_SQS_ENDPOINT}/LotdizDeliveryStartNotificationQueue.fifo
      project-due-date-notification-queue:
        name: LotdizProjectDueDateNotificationQueue
        url: ${AWS_SQS_ENDPOINT}/LotdizProjectDueDateNotificationQueue
      project-funding-rate-fail-notification-queue:
        name: LotdizProjectFundingRateFailNotificationQueue
        url: ${AWS_SQS_ENDPOINT}/LotdizProjectFundingRateFailNotificationQueue
      project-funding-amount-complete-notification-queue:
        name: LotdizProjectFundingAmountCompleteNotificationQueue
        url: ${AWS_SQS_ENDPOINT}/LotdizProjectFundingAmountCompleteNotificationQueue
