server:
  port: 8084
spring:
  config:
    activate:
      on-profile: local,dev,prod
  application:
    name: notification-service
  # config service settings
  cloud:
    config:
      name: notification-service
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh
