-- H2 2.1.214; 
SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS "SA" SALT 'c5d91be9e5ae2b4b' HASH '4bf455446501bad11821411d9676edf1911f640cea9c19a38b405681d9d86e8b' ADMIN;          
CREATE MEMORY TABLE "PUBLIC"."member_notification"(
    "member_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "member_notification_is_read" BOOLEAN NOT NULL,
    "notification_id" BIGINT
);               
ALTER TABLE "PUBLIC"."member_notification" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("member_id");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.member_notification;      
CREATE MEMORY TABLE "PUBLIC"."notification"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "notification_content" CHARACTER VARYING(255) NOT NULL,
    "notification_title" CHARACTER VARYING(255) NOT NULL
);          
ALTER TABLE "PUBLIC"."notification" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("id");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.notification;             
ALTER TABLE "PUBLIC"."member_notification" ADD CONSTRAINT "PUBLIC"."FKd59lsqqgsrspgt54x09f113l0" FOREIGN KEY("notification_id") REFERENCES "PUBLIC"."notification"("id") NOCHECK;              
