-- H2 2.1.214; 
SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS "SA" SALT '4b9894fa758f527a' HASH '09c4966be76100e14ca3426a49aa3645a056ed334117d5f941537f8d8f3dd060' ADMIN;          
CREATE MEMORY TABLE "PUBLIC"."member_notification"(
    "member_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "member_notification_is_read" BOOLEAN NOT NULL,
    "notification_id" BIGINT NOT NULL
);      
ALTER TABLE "PUBLIC"."member_notification" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("member_id", "notification_id"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.member_notification;      
CREATE MEMORY TABLE "PUBLIC"."notification"(
    "notification_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "notification_content" CHARACTER VARYING(255) NOT NULL,
    "notification_title" CHARACTER VARYING(255) NOT NULL
);             
ALTER TABLE "PUBLIC"."notification" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("notification_id");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.notification;             
ALTER TABLE "PUBLIC"."member_notification" ADD CONSTRAINT "PUBLIC"."FKd59lsqqgsrspgt54x09f113l0" FOREIGN KEY("notification_id") REFERENCES "PUBLIC"."notification"("notification_id") NOCHECK; 
